name: Salt Linter

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Salt Lint Action
    steps:
      - uses: actions/checkout@v4
      
      - name: Run salt-lint
        uses: roaldnefs/salt-lint-action@v0.0.3
